# Generated by Django 5.2.3 on 2025-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_stars_comment_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='approval',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending'),
        ),
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.CharField(choices=[('draft', 'پیشنویس'), ('published', 'منتشر شده')], default='draft'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('approved', 'تأیید شده'), ('pending', 'در انتظار تأیید'), ('rejected', 'رد شده')], default='pending', max_length=28),
        ),
    ]
