# Generated by Django 5.2.1 on 2025-08-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
